version: '3.7'

services:
    mysql:
        image: mysql:8.0
        container_name: project_one_mysql
        hostname: project_one_mysql
        restart: on-failure
        ports:
            - "33306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql:cached
            - ./docker/mysql/log:/var/log/mysql:cached
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: magento
            MYSQL_USER: magento
            MYSQL_PASSWORD: magento

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
        volumes:
            - ./docker/elastic/data:/usr/share/elasticsearch/data
        container_name: project_one_elasticsearch
        environment:
            - cluster.name=docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"

    maildev:
        image: djfarrelly/maildev
        container_name: project_one_maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "1025:25"
          - "1080:80"
